package com.ascland.cascade.pojo;

public class TTeacher {


    @Override
    public String toString() {
        return "TTeacher{" +
                "tId=" + tId +
                ", tName='" + tName + '\'' +
                ", tGender='" + tGender + '\'' +
                ", tAge='" + tAge + '\'' +
                '}';
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_teacher.t_id
     *
     * @mbggenerated
     */
    private Integer tId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_teacher.t_name
     *
     * @mbggenerated
     */
    private String tName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_teacher.t_gender
     *
     * @mbggenerated
     */
    private String tGender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_teacher.t_age
     *
     * @mbggenerated
     */
    private String tAge;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_teacher.t_id
     *
     * @return the value of t_teacher.t_id
     * @mbggenerated
     */
    public Integer gettId() {
        return tId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_teacher.t_id
     *
     * @param tId the value for t_teacher.t_id
     * @mbggenerated
     */
    public void settId(Integer tId) {
        this.tId = tId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_teacher.t_name
     *
     * @return the value of t_teacher.t_name
     * @mbggenerated
     */
    public String gettName() {
        return tName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_teacher.t_name
     *
     * @param tName the value for t_teacher.t_name
     * @mbggenerated
     */
    public void settName(String tName) {
        this.tName = tName == null ? null : tName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_teacher.t_gender
     *
     * @return the value of t_teacher.t_gender
     * @mbggenerated
     */
    public String gettGender() {
        return tGender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_teacher.t_gender
     *
     * @param tGender the value for t_teacher.t_gender
     * @mbggenerated
     */
    public void settGender(String tGender) {
        this.tGender = tGender == null ? null : tGender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_teacher.t_age
     *
     * @return the value of t_teacher.t_age
     * @mbggenerated
     */
    public String gettAge() {
        return tAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_teacher.t_age
     *
     * @param tAge the value for t_teacher.t_age
     * @mbggenerated
     */
    public void settAge(String tAge) {
        this.tAge = tAge == null ? null : tAge.trim();
    }
}